build:
	docker-compose -f docker-compose-test.yml build

up:
	docker-compose -f docker-compose-test.yml up -d

down:
	docker-compose -f docker-compose-test.yml down

bu:
	docker-compose -f docker-compose-test.yml up -d --build

in:
	docker exec -it testing_web bash