version: '3.7'

services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 3s
  web:
    container_name: web
    build:
      context: ../src
      dockerfile: Dockerfile
    restart: always
    volumes:
      - files_volume:${MOUNTPOINT}
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    depends_on:
      db:
        condition: service_healthy
    env_file:
       - ./.env

volumes:
  postgres:
  files_volume: